FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 5173

# Har safar yonganda installni tekshirib keyin ishga tushadi
CMD sh -c "npm install && npm run dev -- --host"