FROM php:8.3-fpm

RUN apt-get update && apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev zip git unzip && \
    docker-php-ext-install pdo pdo_mysql

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html
COPY . .

EXPOSE 8000

# Birinchi install qiladi, keyin key yaratadi, keyin serverni yoqadi
CMD bash -c "composer install && php artisan key:generate && php artisan serve --host=0.0.0.0 --port=8000"